info:
  component: Zwitscher Config Server

management.endpoint:
  info:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true

server:
  port: 8888

management.server.servlet:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: INFO
    org.springframework.cloud: INFO

eureka:
  instance:
    # register with IP addresses (required for deployment in Kubernetes?)
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${management.server.servlet.context-path}/info
    healthCheckUrlPath: ${management.server.servlet.context-path}/health

---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config

---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qaware/cloud-native-zwitscher/tree/master/zwitscher-config/src/main/resources/config
          cloneOnStart: true