turbine:
  appConfig: zwitscher-service,zwitscher-board
  instanceUrlSuffix: /admin/hystrix.stream
  clusterNameExpression: appGroupName
  aggregator:
    clusterConfig: ZWITSCHER
management:
  endpoints:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      enabled: true
    web:
      exposure:
        include: '*'
      base-path: /admin
logging:
  level:
    com.netflix.discovery: INFO
    com.netflix.turbine: INFO
    org.springframework.cloud: INFO
    org.springframework.web: INFO




eureka:
  instance:
    # register with IP addresses (required for deployment in Kubernetes?)
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health