board:
  title: Zwitscher Board UI
  headline: Random Quote on Design
  zwitscherUrl: http://zwitscher-service/tweets?q={q}

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
    de.qaware.cloud.nativ.zwitscher: DEBUG

management:
  endpoints:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      enabled: true
    web:
      exposure:
        include: '*'
      base-path: /admin
eureka:
  instance:
    # register with IP addresses (required for deployment in Kubernetes?)
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health
  client:
    healthcheck:
      enabled: true