zuul:
  ignoredPatterns: /**/admin/**
  routes:
    api:
      path: /api/**
      serviceId: zwitscher-service
      stripPrefix: true
    web:
      path: /**
      serviceId: zwitscher-board



logging:
  level:
    com.netflix.discovery: INFO
    org.springframework.cloud: INFO
    org.springframework.web: DEBUG
    de.qaware.cloud.nativ.zwitscher: DEBUG

management:
  server.servlet.context-path: /admin
  endpoints:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      enabled: true
eureka:
  instance:
    # register with IP addresses (required for deployment in Kubernetes?)
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${management.server.servlet.context-path}/info
    healthCheckUrlPath: ${management.server.servlet.context-path}/health