board:
  title: Zwitscher Board UI (Docker)
  headline: Random Quote on Design (Docker)
  zwitscherUrl: http://zwitscher-service/tweets?q={q}

endpoints:
  info:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
    sensitive: false
    web:
      exposure:
        include: '*'
      base-path: /admin
logging:
  level:
    com.netflix.discovery: INFO
    org.springframework.cloud: INFO
    org.springframework.web: DEBUG
    de.qaware.cloud.nativ.zwitscher: DEBUG

eureka:
  instance:
    # register with IP addresses (required for deployment in Kubernetes?)
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health