info:
  component: Zwitscher Eureka Server

server:
  port: 8761

management:
  server.servlet:
    context-path: /admin
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
    health:
      enabled: true

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false